apiVersion: apps/v1
kind: Deployment
metadata:
  name: clould-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clould-client
    spec:
      containers:
        - name: clould-client
          image: vaibhav932000/tripplanner:frontend
          ports:
            - containerPort: 80
              name: http-port
  selector:
    matchLabels:
      app: clould-client