apiVersion: v1
kind: Service
metadata:
  name: cloudl-client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: cloudl-client
  type: LoadBalancer