apiVersion: v1
kind: Service
metadata:
  name: clould-client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: clould-client
  type: LoadBalancer