apiVersion: apps/v1
kind: Deployment
metadata:
  name: clould-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clould-server
    spec:
      containers:
        - name: clould-server
          image: tarinik/my_repo_tarini:backend
          ports:
            - containerPort: 8000
              name: nodejs-port
  selector:
    matchLabels:
      app: clould-server